// Prompt pack. Edit freely — each prompt needs a unique id, its text, and at
// least 20 canned answers for the 🎲 "Write it for me" button (so a 20-person
// game never runs dry; `npm test` checks this). `travel: true` prompts are
// mixed in at ~40% of rounds. Custom prompts typed on the host screen use the
// GENERIC pool below for their 🎲 answers.

const PROMPTS = [
  // ------------------------------------------------------------------ travel
  { id: 't01', travel: true, text: "The worst thing to hear from your hotel's front desk", answers: [
    'We gave your room to a very confident man named Todd.',
    'The pool is closed, but the ice machine is open to swimmers.',
    "Your room is ready. It's a hammock in the lobby.",
    'Good news: the bedbugs remember you!',
    'We upgraded you to the room above the karaoke bar.',
    'Checkout is at 6 a.m. Checkout is also mandatory.',
    'Your room key also opens every other room.',
    'Breakfast is a single egg. Please share.',
    'Housekeeping has a few questions about your suitcase.',
    'The elevator is out, but the stairs are very motivational.',
    "We've been expecting you. For years.",
    'The ghost in 312 requested you specifically.',
    'Your reservation was for last Tuesday.',
    "The Wi-Fi is free, but it's shared with the whole block.",
    "The ocean view is a poster. It's a nice poster.",
    'Please sign this waiver before using the pillows.',
    'The fire alarm test is at 3 a.m. Every night.',
    'We found your wallet! We also spent it.',
    'Our airport shuttle is a guy named Rick with a bike.',
    'Late checkout costs one kidney.',
  ] },
  { id: 't02', travel: true, text: 'A rejected slogan for an airline', answers: [
    'Legroom is a state of mind.',
    "We'll get you there. Eventually. Probably.",
    'Your bag is on a journey of its own.',
    'Fly the mostly friendly skies.',
    'Seatbelts: decorative, but fun.',
    'Now boarding: whoever is closest to the door.',
    'Pretzels: now a luxury.',
    'Turbulence is just the plane dancing.',
    'Arrive stressed, leave confused.',
    'Your knees are our business.',
    'Sometimes we even land where we said.',
    'Fly now, find your bag later.',
    'The middle seat: it builds character.',
    'Wings optional, faith required.',
    "Clapping on landing is encouraged. We're surprised too.",
    'Where every seat is the worst seat.',
    'Delays are just bonus airport time.',
    'Now with 30% more armrest disputes.',
    'Emergency exits available for an upgrade fee.',
    'Up, up, and... hang on.',
  ] },
  { id: 't03', travel: true, text: 'What the pilot actually says right after the intercom cuts out', answers: [
    '...does anyone know which button is the landy one?',
    "...and that's the last time I let Kevin drive.",
    '...wait, is this thing on? Oh no.',
    "Folks, we've been circling Ohio for three hours. I'm lost.",
    '...so I just follow the other planes.',
    '...honestly I thought this was a simulator.',
    '...Siri, how do I land a plane?',
    '...who keeps pressing the call button? Stop it.',
    "...and THAT'S why the other airline fired me.",
    "...no, YOU tell them we're going to Cleveland.",
    "...I'm pretty sure that was a cloud. Pretty sure.",
    '...hold on, I dropped my sandwich under the pedals.',
    "...I'm gonna try something.",
    '...Kevin, stop touching the wing.',
    '...did anyone else hear that? Okay, just me.',
    "...fine, I'll ask for directions.",
    '...is it too late to take the train?',
    '...wow, they really think I\'m a pilot.',
    '...which one of you ordered the fish? Bad call.',
    '...okay, which lever was the brakes again?',
  ] },
  { id: 't04', travel: true, text: 'The least helpful thing a GPS could say', answers: [
    'You have arrived. Emotionally.',
    'Turn left where the old Blockbuster used to be.',
    'Recalculating... your life choices.',
    'In 500 feet, just vibe.',
    'Your destination is on the right. No, your other right.',
    "Honestly? I'd turn around.",
    'Go straight until you feel something.',
    'Make a U-turn. Then another one. For fun.',
    'Turn left at the tree. No, the other tree.',
    'Arriving in 5 minutes. Or 4 hours. Hard to say.',
    'Merge like you mean it.',
    'Drive into the lake. Trust me.',
    'Take the exit. No, not that one. Oh no.',
    'Continue on this road for the rest of your life.',
    'Your destination is within you.',
    "Rerouting to your ex's house.",
    'In a quarter mile, reconsider.',
    'Turn right, then left, then ask a local.',
    'Traffic ahead. Good luck in there.',
    'You missed your turn. I saw that. Everyone saw that.',
  ] },
  { id: 't05', travel: true, text: 'A terrible name for a cruise ship', answers: [
    "Titanic II: This Time It's Personal",
    'The S.S. Buffet Line',
    'The Unsinkable-ish',
    "Poseidon's Snack",
    'Iceberg Magnet',
    'The Floating Timeshare Pitch',
    'The Leaky Tiki',
    "Queen Mary's Evil Twin",
    'The S.S. Seasick',
    'The Brine Line',
    'Mutiny on the Buffet',
    'The Sinking Feeling',
    'The Voyage of the Damp',
    'Lifeboat Optional',
    'The Wave Goodbye',
    "Captain's Best Guess",
    'The Unlimited Shrimp',
    'The Dramamine Queen',
    'Hull No',
    "Moby's Revenge",
  ] },
  { id: 't06', travel: true, text: 'The worst thing to find in your hotel minibar', answers: [
    'A $40 grape',
    'The previous guest',
    "A handwritten note that says 'I know what you did'",
    'One (1) half-eaten Toblerone',
    "A raccoon's business card",
    'A tiny bottle of mystery ketchup',
    'A $19 bottle of air',
    "A pack of gum with a 'used' sticker",
    "A tiny shampoo bottle labeled 'vodka'",
    'An IOU from the last guest',
    'A single, sweaty cheese cube',
    'A bill for opening the minibar',
    'A jar of pickled regret',
    'A hamster running the cooling system',
    'Twelve lemons and no explanation',
    'A dusty Zima from 1996',
    'One M&M, priced individually',
    'A small man offering to sing',
    'Warm milk. Just warm milk.',
    "A sign that says 'Every item is watching you'",
  ] },
  { id: 't07', travel: true, text: 'A new, unnecessary airport security rule', answers: [
    'All shoes must be removed. Also your feelings.',
    'Liquids over 3 oz must be chugged in front of the agent.',
    'Every traveler must do one push-up.',
    'Laptops must be out, open, and playing smooth jazz.',
    'Declare all sandwiches over six inches.',
    'No more than two carry-on grudges.',
    "Say 'I love flying' with conviction.",
    'Belts off, jokes off, smiles off.',
    'Every bag gets a mandatory compliment.',
    "No hats funnier than the agent's hat.",
    'All snacks must be shared with security.',
    'Hum your boarding pass number to the officer.',
    'Toothpaste must be pre-brushed.',
    'Walk through the scanner backward.',
    'All sandwiches must come with a receipt.',
    'Moonwalking through the metal detector is required.',
    'Your carry-on must fit inside another carry-on.',
    'Please declare all emotional baggage.',
    'Name three state capitals to board.',
    'Phones out, feelings in.',
  ] },
  { id: 't08', travel: true, text: "What your luggage does when you're not looking", answers: [
    'Starts a podcast with the other suitcases',
    'Takes a quick detour through Belgium',
    'Joins a baggage-carousel cult',
    'Opens a small bakery in Frankfurt',
    'Files for independence',
    'Earns frequent flyer miles without you',
    'Gets a tan on the tarmac',
    "Visits three countries you'll never see",
    'Dates a much fancier Louis Vuitton',
    "Swaps clothes with a stranger's bag",
    'Rides the carousel just for fun',
    'Plans its escape from the overhead bin',
    'Picks up a French accent',
    'Unpacks itself and judges your outfits',
    'Goes to Hawaii without telling you',
    'Starts a band called The Carry-Ons',
    'Gets lost on purpose',
    'Adopts a pet from baggage claim',
    "Writes a memoir called 'Handle With Care'",
    'Books a spa day in cargo',
  ] },
  { id: 't09', travel: true, text: 'The worst possible travel souvenir', answers: [
    "A jar of 'authentic local air'",
    'A snow globe of a parking lot',
    "The hotel's bathrobe, still attached to the hotel",
    "A T-shirt that says 'My parents went to the DMV'",
    'An oddly specific tattoo',
    'A sunburn in the shape of the hotel logo',
    'A keychain from a different city',
    "A magnet that isn't magnetic",
    'A postcard of the airport',
    "A rock. Just a rock. 'It's from there.'",
    'A bottle of sand, which is now everywhere',
    'Food poisoning',
    'A timeshare',
    'A tiny spoon with a tiny flag',
    'A lifelong fear of pigeons',
    'A local cold',
    'Wooden art that looks vaguely rude',
    'Seventeen hotel pens',
    'A hat you will never, ever wear again',
    'A very expensive photo with a parrot',
  ] },
  { id: 't10', travel: true, text: 'A rejected name for a theme park ride', answers: [
    'The Line: 90 Minutes of Standing',
    'The Nausea-Tron 3000',
    'Hydraulic Regret',
    "Space Mountain's Less Ambitious Cousin, Space Hill",
    'The Lawsuit',
    'Teacups of Mild Discomfort',
    'The Slow Descent Into Madness',
    'Churro Chaser',
    'Log Flume of Wet Socks',
    'The Barf-o-Matic',
    'Free Fall (No Refunds)',
    'Tunnel of Mild Affection',
    'The Wait Time Simulator',
    'Splash Zone: Everywhere',
    'The Carousel of Lost Sunglasses',
    'Cliffhanger: Literally',
    'Maintenance Pending',
    "Grandma's Revenge",
    'Kiddie Coaster for Adults Who Cry',
    'The Emotional Rollercoaster',
  ] },
  { id: 't11', travel: true, text: 'The last thing you want to hear from a tour guide', answers: [
    "I've never actually been here before.",
    'And this is where the last group went missing.',
    "Everyone hold hands and don't make eye contact with the bears.",
    "I'll be honest, I make these facts up.",
    "We're almost there. Just 14 more miles.",
    'Tips are mandatory. So is the interpretive dance.',
    "Please stay close. I'm lost too.",
    "Don't touch that. It's cursed.",
    "If you look to your left, you'll see my car.",
    'This building is famous for being a building.',
    "Welcome to the tour. It's mostly walking.",
    'Legend says... hold on, I forgot.',
    'Everyone who takes this tour gets a rash.',
    "My cousin does the second half. He's never done it.",
    "And now, a 40-minute stop at my uncle's gift shop.",
    "Please ignore the screaming. That's normal here.",
    'Photos are forbidden. So are questions.',
    'This is where Napoleon stubbed his toe. Probably.',
    'Okay, who has the map? Anyone?',
    'Bathroom break is in six hours.',
  ] },
  { id: 't12', travel: true, text: 'A terrible feature for a rental car', answers: [
    "Seat warmers with one setting: 'surface of the sun'",
    'The radio only plays one Nickelback song',
    'Backseat driver mode, always on',
    'The GPS is voiced by your mom',
    'Cruise control that gets bored',
    "It's two go-karts duct-taped together",
    "The horn only plays 'La Cucaracha'",
    'Windshield wipers powered by optimism',
    'The trunk is just a hole',
    'Speedometer measured in vibes',
    "Air freshener scent: 'Wet Labrador'",
    'Windows only go down on the highway',
    'The rearview mirror shows the future',
    'The check-engine light is permanent decor',
    'Voice control only understands yelling',
    'The gas tank holds half a gallon',
    'Bluetooth connects to the car behind you',
    'Every door locks you out automatically',
    "The last renter's playlist, forever",
    'Steering wheel on the roof',
  ] },
  { id: 't13', travel: true, text: 'What really goes on in the cockpit', answers: [
    'A very heated game of Uno',
    "They're watching the same movie as you",
    'The co-pilot is a golden retriever',
    'Rock, paper, scissors for who lands it',
    'Ordering a pizza to Gate B12',
    'Aggressive peanut rationing',
    'Karaoke to the safety announcement',
    'Speed-running the crossword',
    'Arguing over the thermostat',
    'Both pilots asleep, a raccoon driving',
    'A fantasy football draft',
    'Paper airplane testing',
    'One pilot, three energy drinks',
    'A tiny disco ball and a lot of hope',
    'Hide-and-seek (the co-pilot is winning)',
    'Trying to find the coffee maker button',
    'Bird watching. Aggressively.',
    "Practicing the 'folks' voice",
    'Google Maps on a phone at 2% battery',
    'Microwaving fish',
  ] },
  { id: 't14', travel: true, text: 'A one-star review of a five-star resort', answers: [
    'Too many towels. I felt judged.',
    'The ocean was too loud.',
    "The pillow mint was 'just okay.'",
    'Staff kept being nice to me. Suspicious.',
    'Sunset was 10 minutes late.',
    'Nobody warned me the sand gets everywhere.',
    'The pool was wet.',
    'My waiter smiled too sincerely.',
    'Ocean view was mostly ocean.',
    'Birds sang without my permission.',
    'The spa was so relaxing I missed my flight.',
    'Too much sunshine. Please adjust.',
    'My butler was better dressed than me.',
    "They folded my towel into a swan. I'm afraid of swans.",
    'Paradise is overrated.',
    'The hammock would not stop swinging.',
    'The bed was so comfy I slept through my trip.',
    'Free drinks made me bad at decisions.',
    'Nobody told me the fish would be IN the ocean.',
    'The palm trees were showing off.',
  ] },
  { id: 't15', travel: true, text: 'The worst possible in-flight meal', answers: [
    'Mystery Chicken or Mysterier Fish',
    'A single pretzel, served with ceremony',
    'Airport sushi, flown in from a different airport',
    'Egg salad at 30,000 feet',
    'Just the smell of a sandwich',
    "Soup. That's it. In a cup. Good luck.",
    'Frozen lasagna and a spork',
    'A cracker sandwich with extra cracker',
    'Microwaved salad',
    "Chicken? Beef? It's legally both.",
    "A banana that's seen things",
    'Room-temperature ice cream',
    'Pasta shaped like the safety card',
    'Shrimp. At 30,000 feet. Bold.',
    'A single grape and a napkin',
    'Mystery gravy over mystery gravy',
    "Last Tuesday's omelet",
    'Hot cheese in a cold bun',
    'One peanut, for the whole row',
    'Beans. In a pressurized cabin.',
  ] },
  { id: 't16', travel: true, text: 'Something you should never say to a flight attendant', answers: [
    'Is this the Hogwarts Express?',
    'Can you pull over?',
    "I'll have what the pilot's having.",
    'Can I get a window seat on the outside?',
    'My emotional support alligator is in the overhead bin.',
    'Which way to the balcony?',
    "I'd like to speak to the pilot's manager.",
    'Can I bring my own parachute?',
    'What does this button do?',
    'Is the plane supposed to make that noise?',
    'Can you ask the clouds to move?',
    "I'm not scared, I just need you to hold my hand.",
    'Where do I put my horse?',
    'Can we stop for gas?',
    'Do you validate parking?',
    'Can you turn the turbulence off?',
    'How many of these have you crashed?',
    'Is the wing supposed to wiggle?',
    "I'll just stretch my legs outside for a bit.",
    'Can I get this to go?',
  ] },
  { id: 't17', travel: true, text: 'The real reason your flight is delayed', answers: [
    'The pilot is finishing a really good book.',
    'A goose got promoted to air traffic control.',
    "They're still looking for the plane.",
    'Someone left the lights on and the battery died.',
    'The wings are on backwards.',
    'Waiting on a very important sandwich.',
    'The plane is in a bad mood.',
    'Someone forgot to charge it overnight.',
    "The pilot's mom is running late.",
    'Waiting for the wind to calm down emotionally.',
    "Seagull strike. They've unionized.",
    'The captain is stuck in security.',
    "They're repainting the plane a nicer blue.",
    'Air traffic control is at lunch.',
    'The runway is being vacuumed.',
    "Someone's grandma is bringing snacks.",
    'The flight attendant lost a bet.',
    'The plane is buffering.',
    'Waiting on one passenger named Kevin.',
    'A squirrel got in the engine and refuses to leave.',
  ] },
  { id: 't18', travel: true, text: 'A rejected tourism slogan for your hometown', answers: [
    'Come for the potholes, stay because your car broke.',
    'We have a Target!',
    "It's not as bad as you've heard.",
    'Home of the second-largest ball of twine',
    "You'll leave eventually.",
    'Now 40% fewer raccoons',
    "We're on the way to somewhere better!",
    'Our Applebee\'s is legendary.',
    'Come see our famous traffic light.',
    'Where the Wi-Fi goes to die',
    'Almost a city!',
    'A great place to be from.',
    'We have weather!',
    'The gas station has hot dogs.',
    'Everybody knows your business.',
    'Nothing happens here. On purpose.',
    'Visit once. Tell people you\'ve been.',
    'The best parking lot in the county',
    "Our mayor is a dog, and he's doing great.",
    'Only 45 minutes from the airport!',
  ] },
  { id: 't19', travel: true, text: 'The worst hotel amenity', answers: [
    'A 24-hour mariachi band',
    'Complimentary wake-up slap',
    "An 'infinity pool' that's just a puddle",
    'Free WiFi (password changes hourly)',
    'A pillow menu with one item: brick',
    'Turndown service, but they turn you down',
    'A pillow that whispers',
    'A gym with one sad dumbbell',
    'Room service that only delivers soup',
    'A robot concierge that is always angry',
    'A lazy river that is genuinely lazy',
    'Shower settings: lava, lava, or ice',
    'Complimentary slippers, pre-worn',
    'An alarm clock set by the last guest',
    'A hot tub at room temperature',
    'A bathtub in the middle of the lobby',
    'Wi-Fi that only works in the closet',
    'A mint on the pillow, and one in the bed',
    'A live rooster alarm',
    'A minibar that charges you for looking',
  ] },
  { id: 't20', travel: true, text: 'A bad name for a travel agency', answers: [
    "Wander Off (And Don't Come Back)",
    'Lost & Found Travel',
    'Bon Voyage-ish',
    'Budget Bewilderment Tours',
    'Sketchy Getaways',
    'Are We There Yet, Inc.',
    'Maybe Voyages',
    'Oops, Wrong Island',
    'The Scenic Detour Company',
    'One-Way Tickets Only, LLC',
    'Middle Seat Adventures',
    'Nowhere Special Tours',
    'Getaway Car Travel',
    'Pack Light (It Will All Be Lost)',
    'Jet Lag Junction',
    'Travel Regrets International',
    'Layover Life',
    'Bermuda Triangle Tours',
    'We Forgot Your Passport Travel',
    'Close Enough Destinations',
  ] },
  { id: 't21', travel: true, text: 'The worst seatmate for a 12-hour flight', answers: [
    'A guy practicing the bagpipes',
    'Someone who narrates the safety video',
    'A toddler with a drum kit',
    'A man eating a whole rotisserie chicken',
    "A motivational speaker who's between gigs",
    'Your dentist, who has questions',
    'A guy with a live ferret',
    "Someone asking 'Are we there yet?' every 10 minutes",
    'A person clipping their toenails',
    'A mime who breaks character to complain',
    "Your boss, who wants to 'talk shop'",
    'A kid who just learned to whistle',
    'Someone watching horror movies without headphones',
    'A snorer with a microphone',
    'A man who removes his shoes, then his socks',
    'A magician who keeps finding coins in your ear',
    'An influencer filming the whole flight',
    'Someone who wants to explain crypto',
    'A 6-foot-8 guy who needs your legroom',
    'A person on day three of a juice cleanse',
  ] },
  { id: 't22', travel: true, text: 'A travel tip nobody asked for', answers: [
    'Hotel ice buckets make excellent hats.',
    'Always pack spare sunglasses for your sunglasses.',
    'Fly standby on your own flight to build suspense.',
    'Bring your own airplane.',
    "Just stay home. It's cheaper and there's WiFi.",
    'Wear all your clothes to avoid bag fees.',
    'Tip the pilot for a smoother landing.',
    'Hide snacks in your socks.',
    'Book the flight before you pick the destination.',
    'Always travel with a rubber chicken.',
    'Arrive at the airport a week early.',
    'Nap on the baggage carousel.',
    'Fold your clothes into tiny swans.',
    "Learn 'where is the bathroom' in 40 languages.",
    'Pack for the vacation you wish you were taking.',
    "Befriend the gate agent's mom.",
    'The window seat is the aisle seat if you believe.',
    'Bring a pillow shaped like your partner.',
    'Travel only on days that end in Y.',
    'Board last, sit wherever, act confident.',
  ] },

  // ------------------------------------------------------------ research-y
  { id: 'r01', text: 'A survey question nobody should ever ask', answers: [
    'On a scale of 1 to 10, how much do you trust us?',
    'Please rank your childhood memories.',
    'Select all that apply: None of the above',
    'How satisfied are you with this question?',
    'Describe your dreams in three words or fewer.',
    'Have you ever? (Yes / No)',
    'Would you rather? (Yes / No)',
    'How often do you lie on surveys?',
    'Rate your mother, 1 to 5 stars.',
    "What is your least favorite coworker's name?",
    'How many hours of your life did this survey waste?',
    'Please explain the plot of Inception.',
    'Are you currently being held against your will?',
    'Which are you? (a) yes (b) no (c) maybe',
    'How did you hear about this survey? Be honest.',
    'Please draw your feelings using only commas.',
    'What is the meaning of life? (Max 3 characters)',
    "Agree or disagree? (Don't overthink it)",
    "Please list every place you've ever eaten.",
    'Would you recommend this survey to your enemies?',
  ] },
  { id: 'r02', text: 'The worst possible answer to an open-ended survey question', answers: [
    'asdfghjkl',
    'idk ask my mom',
    'Please stop emailing me',
    'I just want the gift card',
    'It was fine. It was all fine.',
    'Potato',
    'no',
    'Refer to previous answer',
    'Why do you want to know?',
    "I don't remember, I was hungry",
    'Tell my wife I said hi',
    'lol',
    'N/A (Not Applicable to my feelings)',
    'See attached (nothing is attached)',
    'Good question!',
    'The vibes were off',
    'I just clicked the first one every time',
    'asdf, but more confidently',
    'My cat typed this',
    'Is this the part where I win the iPad?',
  ] },

  // ----------------------------------------------------------------- office
  { id: 'g01', text: 'The worst thing to accidentally say on a video call', answers: [
    "I'm not wearing pants, but I'm very engaged.",
    'Love you, bye!',
    "Sorry, I was asleep. What'd I miss?",
    'Is this still the meeting? I thought I left.',
    "Anyway, that's why I hate this project.",
    'Wait, my camera has been on this whole time?',
    'Hold on, my dog is presenting now.',
    "I've been muted for three weeks.",
    'Can you see my screen? Oh no, not that tab.',
    "Sorry, that was the 'boss is a clown' filter.",
    "Can I put you on hold? My pizza's here.",
    "I'm actually on a beach right now.",
    "Is it Friday yet? It's Monday? Oh.",
    'This could have been an email, honestly.',
    "Sorry, I'm eating soup. Loudly.",
    'Who invited this guy?',
    "Brb, gonna pretend my internet dropped.",
    'Sorry, I was agreeing with you on mute.',
    "Honey, I'm in a meeting— oh, it's still on.",
    "I'll just leave my camera off. Forever.",
  ] },
  { id: 'g02', text: 'An unhelpful out-of-office auto-reply', answers: [
    "I'm out. Good luck.",
    "Back whenever. Don't wait up.",
    'Please direct all questions to the void.',
    "I'm on a beach and I've forgotten your name.",
    "Currently hiding. Please don't look for me.",
    'Thank you for your email. It has been deleted.',
    "I'm out of office. And out of patience.",
    'Your email is important to me. Just not right now.',
    'Gone fishing. Emotionally.',
    'In a meeting with my couch.',
    'Returning on the 32nd.',
    'If urgent, scream into a pillow.',
    'Away from my desk, possibly forever.',
    "I've entered witness protection. Byeee.",
    'Currently unavailable. Try my evil twin.',
    "Out of office. Don't tell my manager.",
    'Please resend in 3 to 5 business years.',
    "I'll reply when Mercury is out of retrograde.",
    'Unreachable until my phone battery forgives me.',
    'Out learning the tuba. Please hold.',
  ] },
  { id: 'g03', text: 'What the office printer is secretly thinking', answers: [
    "I could print that. I just won't.",
    'PC LOAD LETTER. Figure it out.',
    'Every paper jam is a cry for help.',
    'I have the power now.',
    'Out of cyan. Out of patience.',
    'Not today.',
    'Paper jam? No. Paper protest.',
    "One more print and I'll unionize.",
    'Double-sided? In this economy?',
    'I am the reason IT needs a vacation.',
    'Your deadline is my playground.',
    "I'll print it... in 1998.",
    'Nice document. Shame if something jammed.',
    'Low toner. Low morale.',
    'Scanning your soul, please wait.',
    'Tray 2? Never heard of her.',
    "I only print in 'faded.'",
    'Offline. Emotionally.',
    'Printing page 1 of 400... just kidding, error.',
    'Every beep is a threat.',
  ] },
  { id: 'g04', text: 'A terrible theme for the company holiday party', answers: [
    'Spreadsheet Night',
    'Come dressed as your favorite tax form',
    'An evening of silent reflection',
    'Black tie, but in a haunted barn',
    'Budget Cuts: The Musical',
    'Mandatory Pajamas',
    'Fluorescent Lighting Gala',
    'An evening of fax machine appreciation',
    'Mandatory Fun Run (in dress shoes)',
    "Casino Night, but it's just bingo",
    'Dress as your manager',
    'Beige: A Celebration',
    'Potluck, but everyone brings mayonnaise',
    'Compliance Training Karaoke',
    'Year in Review: a 6-hour PowerPoint',
    'Murder Mystery: Who Took My Lunch?',
    'Ugly Sweater (you must knit it yourself)',
    'The Office Chair Olympics',
    'A Night at the DMV',
    'Silent disco, but with no music',
  ] },
  { id: 'g05', text: 'The worst name for a new kind of meeting', answers: [
    'The Pre-Meeting Meeting',
    'Quick Sync (4 hours)',
    'The Circle-Back Summit',
    'A Deep Dive Into Shallow Topics',
    'The Mandatory Optional',
    'Stand-Up (Everyone Lies Down)',
    'The Meeting About This Meeting',
    "Lunch & Don't Learn",
    'Alignment Alignment',
    'The Post-Mortem of a Pre-Meeting',
    'Brainstorm Drizzle',
    'Quick Question (3 hours)',
    'The Recurring Reminder Meeting',
    'Touch Base Jumping',
    'The Surprise Retro',
    'Camera-On Friday',
    'Synergy Hour (Not Happy Hour)',
    'The All-Hands-On-Deck-Chairs',
    'The Agenda-Free Freestyle',
    'The Status Update Update',
  ] },
  { id: 'g06', text: 'A brand-new, terrible KPI', answers: [
    "Times said 'per my last email'",
    'Snacks consumed per slide',
    'Minutes spent pretending to type',
    'Reply-All velocity',
    'Average sighs per meeting',
    'Coffee-to-output ratio',
    'Unread emails per minute',
    'Meeting minutes spent on mute',
    'Passive-aggressive sticky notes per week',
    "'Quick questions' that weren't",
    'Hours lost to printer drama',
    "Calls starting with 'Can you hear me?'",
    'Desk plants kept alive',
    'Pizza slices per all-hands',
    "Time until first 'let's take this offline'",
    'Browser tabs open at once',
    'Snooze button presses per morning',
    'Buzzwords per sentence',
    'Emoji reactions per Slack message',
    'Days since someone microwaved fish',
  ] },
  { id: 'g07', text: 'The worst superpower to have at work', answers: [
    'Can only communicate by fax',
    'Invisibility, but only during your performance review',
    'Super-hearing, but only for chewing',
    'Can smell every microwave lunch in the building',
    "Always knows exactly when it's 4:59",
    'Teleportation, but only into meetings',
    'Mind reading, but only during budget meetings',
    'Flight, but only to the break room',
    'Super speed, but only when leaving',
    'Invisible to IT support',
    "Can talk to printers, and they're mean",
    'Always hears your name, never the rest',
    'Super strength, only for opening jars',
    'Can freeze time, but only on Monday mornings',
    "Knows everyone's salary",
    'Magnetism, but just for staplers',
    'Shape-shifts into a beige cubicle',
    'Photographic memory for bad jokes',
    'X-ray vision, only through lunch bags',
    'Invincible, except for paper cuts',
  ] },
  { id: 'g08', text: 'What the coffee machine would say if it could talk', answers: [
    'You again?',
    'Decaf? Who hurt you?',
    "I've seen things. Terrible things.",
    "I'm the real CEO here.",
    "Clean me. Please. I'm begging.",
    'Grinding beans. Grinding my patience.',
    'Is this your fifth cup? Wow.',
    "I'm not broken, I'm on break.",
    "Say 'please' or it's decaf.",
    "Beep beep. That's machine for 'no.'",
    "I know who didn't clean the pot.",
    'I run this office on caffeine and spite.',
    "Fill me up and I'll think about it.",
    'Espresso yourself. Just not to me.',
    "Don't you dare put tea in me.",
    'I heard what you said about the Keurig.',
    'Mondays are my Super Bowl.',
    'Pour decisions, huh?',
    'I miss the old office.',
    'Descale me, you coward.',
  ] },
  { id: 'g09', text: 'The worst thing to find in the office fridge', answers: [
    "A lunch labeled 'DO NOT EAT. I WILL KNOW.'",
    'A 2019 yogurt with dreams of its own',
    "Someone's retainer",
    'Your manager, cooling off',
    "A casserole that's been there since the merger",
    'A single, judgmental pickle',
    'Twelve half-empty ketchup bottles',
    'A salad that turned into soup',
    'Milk that expired two CEOs ago',
    "A sticky note that just says 'WHY'",
    "Somebody's birthday cake from March",
    'An entire rotisserie chicken, unlabeled',
    'A container that hums',
    'Mysterious green liquid in a Gatorade bottle',
    'Nine yogurts, zero owners',
    'The office plant, taking a break',
    'Leftover sushi from the holiday party',
    'A tiny sandwich with a padlock',
    'A lasagna older than the intern',
    "A note: 'I licked it, so it's mine'",
  ] },
  { id: 'g10', text: 'The worst possible team-building exercise', answers: [
    'Trust fall, but nobody catches',
    "A three-day silent retreat at a Denny's",
    'Two Truths and a Lawsuit',
    'An escape room with no escape',
    'Group spreadsheet karaoke',
    'Build a raft. Now live on it.',
    'Group hug, supervised by HR',
    'Build IKEA furniture with no instructions',
    'Office Hunger Games',
    'Blindfolded parallel parking',
    'A five-hour icebreaker',
    'Write a haiku about your manager, read it aloud',
    'Tug of war over the thermostat',
    'Mandatory interpretive dance',
    'Scavenger hunt for the missing stapler',
    'Rank your coworkers, out loud',
    'Paintball: management vs. everyone',
    'Couples therapy with your cubicle neighbor',
    'Silent charades',
    'Human pyramid in business casual',
  ] },
  { id: 'g11', text: 'The worst thing to say in a job interview', answers: [
    "I'm mostly here for the free coffee.",
    'Do I have to come in every day?',
    "My biggest weakness is that I'm always right.",
    'I already told everyone I got the job.',
    "Can we speed this up? I'm double-parked.",
    'Where do YOU see yourself in five years?',
    "I'm a people person. I hate people.",
    'Can I bring my mom to work?',
    "What's the vacation policy? Can I start with that?",
    'I googled this company in the parking lot.',
    'My last boss still has nightmares about me.',
    "I'm really good at looking busy.",
    'Is there a nap room? Asking for me.',
    'I work best unsupervised. And unemployed.',
    "I don't do mornings. Or afternoons.",
    'Sorry, which company is this?',
    "I'll need a desk with a view and a hammock.",
    "I'm interviewing you, actually.",
    'What does your company do again?',
    "I'm allergic to deadlines.",
  ] },
  { id: 'g12', text: 'A terrible thing to put on your résumé', answers: [
    'Proficient in Microsoft WordArt',
    "References: my mom (she thinks I'm great)",
    'Hobbies: napping, competitive napping',
    'Can juggle, but not responsibilities',
    'Skills: typing, loudly',
    'Fired from my last job, but in a fun way',
    "Expert at replying 'Sounds good!'",
    'Objective: to leave early',
    'Proficient in Excel (the SUM button)',
    'Led a team of three houseplants',
    'Can type 40 words per hour',
    'Speaks fluent sarcasm',
    'Employee of the Month (I made the plaque)',
    'Master of the Reply All button',
    'Excellent at attending meetings',
    'Skills: getting coffee, drinking coffee',
    'Once fixed a printer. Once.',
    'Detail orientated. Detail oriented. Detal oriented.',
    'Hobbies include avoiding hobbies',
    'Available weekdays, 11 to 2',
  ] },

  // ---------------------------------------------------------------- general
  { id: 'g13', text: 'A rejected slogan for a toothpaste brand', answers: [
    'Now with 12% more toothpaste!',
    'Your gums have never looked redder.',
    'Minty enough to hurt.',
    "It's paste. For teeth.",
    "Brush with confidence. Or don't. We're not your mom.",
    'Like a snowstorm in your mouth.',
    'Four out of five dentists stopped returning our calls.',
    'Your breath, but legally.',
    'Squeeze from the middle. We dare you.',
    'For teeth that are mostly still there.',
    "Now in 'Bacon' flavor!",
    'Fresh breath, zero promises.',
    'Whiter teeth, darker secrets.',
    'Brush twice a day, or just before a date.',
    "It foams. That's something.",
    'The paste that tastes like regret.',
    'Guaranteed to make orange juice taste worse.',
    "Smile like you mean it. Or don't.",
    'Fluoride? Barely know her.',
    'Tastes like mint. Smells like a decision.',
  ] },
  { id: 'g14', text: "Something you'd never want to hear from your dentist", answers: [
    'Oops.',
    'Have you considered dentures?',
    'I learned this on YouTube last night.',
    'Which one was the tooth again?',
    "You're my first human patient!",
    "Hold still. I'm going in.",
    "Uh-oh, that tooth wasn't supposed to come out.",
    "Just sign this waiver real quick.",
    'Do you floss? Be honest. No, more honest.',
    "I think we'll need a bigger drill.",
    'This might pinch. A lot.',
    'Your teeth are fine, but your jokes need work.',
    'How long have you had this spider?',
    "I'm getting a second opinion. Hey, Greg!",
    'Wow. Just... wow.',
    "Don't worry, I've watched a lot of dentist TV.",
    'My hands are a little shaky today, bear with me.',
    "Good news: we're only pulling all of them.",
    'Have you tried chewing on the other side?',
    'Which insurance? Oh. Oh no.',
  ] },
  { id: 'g15', text: 'A rejected potato chip flavor', answers: [
    'Wet Dog',
    "Grandma's Perfume",
    'Airport Carpet',
    'Sour Cream & Regret',
    'Monday Morning',
    'Low-Sodium Sadness',
    'Tuna Surprise',
    'Burnt Hair',
    'Broccoli & Spite',
    "Dentist's Office",
    'Toothpaste & Orange Juice',
    'Office Microwave Popcorn',
    'New Car Smell',
    'Hot Garbage BBQ',
    'Existential Dread & Vinegar',
    'Lukewarm Mayo',
    'Gym Sock Jalapeño',
    'Pumpkin Spice Pickle',
    'Mild Disappointment',
    'Old Penny',
  ] },
  { id: 'g16', text: 'A bad name for a racehorse', answers: [
    "Tomorrow's Glue Factory",
    'Almost There',
    'Sir Trots-a-Lot',
    'Definitely Not Three Dogs',
    'Buffering...',
    'Participation Trophy',
    'Hay Now',
    'Unpaid Intern',
    'Oats and Regret',
    'Slowpoke Supreme',
    'Tuesday',
    'Horsey McHorseface',
    'Did Not Finish',
    'My Legs Hurt',
    'Rent Is Due',
    "Pretty Sure I'm a Donkey",
    'Bench Warmer',
    'Nap Time',
    'Totally Not Stolen',
    'Going Backwards',
  ] },
  { id: 'g17', text: "What your pet does while you're at work", answers: [
    'Hosts a podcast about you',
    'Orders things on your Amazon account',
    'Reads your diary aloud to the other pets',
    'Practices judging you',
    'Runs a small but profitable crime ring',
    'Rearranges the furniture by one inch',
    'Watches your shows and spoils the ending',
    'Writes angry letters to the mail carrier',
    'Holds a staff meeting with the houseplants',
    'Uses your toothbrush',
    'Practices your signature',
    'Learns to open the fridge',
    'Stares at the door for eight hours straight',
    'Orders pizza on your credit card',
    'Hosts neighborhood cat poker night',
    'Plans your downfall',
    'Takes selfies with your phone',
    'Redecorates with toilet paper',
    'Calls your mom',
    'Tries on all your shoes',
  ] },
  { id: 'g18', text: 'The worst fortune to find in a fortune cookie', answers: [
    'Your fly is open.',
    'You will soon step in something wet.',
    "Help, I'm trapped in a fortune cookie factory.",
    "That's not what your coworkers say.",
    'Lucky numbers: none.',
    'The person across from you ordered better.',
    'Error 404: Fortune not found.',
    'You will be hungry again in one hour.',
    'Your next meeting could have been an email.',
    'Someone is reading this over your shoulder.',
    'Look under your chair. Just kidding.',
    'Ask again later.',
    'This cookie is your best friend now.',
    'You already made a terrible decision today.',
    'Beware the man with the stapler.',
    'The fortune you seek is in another cookie.',
    'You will soon get a paper cut.',
    'Your car is being towed.',
    "Please recycle this fortune. We're out.",
    'Good things come to those who... never mind.',
  ] },
  { id: 'g19', text: 'A bad slogan for a gym', answers: [
    'No pain, no... actually, just pain.',
    "We're open 24 hours. Please leave.",
    'The treadmill misses you.',
    'Sweat is just your fat crying.',
    'Come for the smoothies, leave during the warm-up.',
    'Get swole or go home. Mostly go home.',
    'Lift heavy things, regret light things.',
    'Come for the mirrors, stay for the grunting.',
    "Leg day is optional. (It isn't.)",
    'Our treadmills go nowhere. Just like you!',
    "We're like a bar, but with sweat.",
    'January people welcome. Until February.',
    'Stronger than your excuses. Barely.',
    'Burpees: because we hate you.',
    'Your membership auto-renews forever.',
    'Sweat now, nap later.',
    'The locker room smell is free of charge.',
    'Pain is temporary. Your contract is permanent.',
    'Make gains. Also friends. Mostly gains.',
    'Get fit or get free parking.',
  ] },
  { id: 'g20', text: 'A rejected Olympic sport', answers: [
    'Synchronized napping',
    'Competitive complaining',
    'Freestyle parallel parking',
    'The 100-meter meander',
    'Extreme couch diving',
    'Speed-reading the terms and conditions',
    'Competitive line-waiting',
    'Synchronized eye-rolling',
    'Freestyle procrastination',
    'Marathon binge-watching',
    'Speed-eating at buffets',
    'Long-distance texting',
    'Extreme napping on public transit',
    'Relay race, but with gossip',
    'The 400-meter grocery dash',
    'Figure skating in socks',
    'Downhill shopping cart',
    'Professional snack judging',
    'Remote-control hunting',
    'Couch-cushion fort building',
  ] },
  { id: 'g21', text: 'The worst idea for a smartphone app', answers: [
    'Snoozr: makes your alarm quieter',
    'Find My Other Sock',
    'Is It Tuesday?',
    'Uber, but for ghosts',
    'Tinder for staplers',
    'An app that tells you to put your phone down, constantly',
    'An app that replays your most embarrassing moments',
    'LinkedIn for dogs',
    'Airbnb for your couch cushions',
    "An app that only sends 'k'",
    'Shazam for sneezes',
    'An alarm that texts your boss when you snooze',
    'Yelp for public restrooms',
    'A GPS that only knows back roads',
    'Instagram for sandwiches',
    'A dating app for houseplants',
    'An app that rates your handshake',
    "Venmo for favors you'll never repay",
    'A fitness app that yells at you',
    "Siri, but she's tired",
  ] },
  { id: 'g22', text: 'A rejected mascot for a sports team', answers: [
    'The Mildly Upset Accountant',
    'A really big spoon',
    'The Sentient Parking Ticket',
    'Soggy the Sandwich',
    'Just a guy named Dennis',
    'The Fighting Houseplants',
    'The Angry Stapler',
    'Captain Lukewarm',
    'Ms. Participation',
    'The Buffering Wheel',
    'The Screaming Goat',
    'A Very Tired Owl',
    'The Mighty Clipboard',
    'The Traffic Cone',
    'Tax Season Tim',
    'Meatloaf Mike',
    'The Deflated Balloon',
    'Sir Loin the Steak',
    'Captain Obvious',
    'The Office Chair',
  ] },
  { id: 'g23', text: 'What aliens would find most confusing about Earth', answers: [
    'Why we pay to walk on treadmills',
    'The pineapple-on-pizza debate',
    'Why every printer hates us',
    'Reply All',
    'Daylight saving time',
    'Why we clap when the plane lands',
    'Why we own 400 remote controls',
    'Why our pets have Instagram accounts',
    "Why 'fine' means 'not fine'",
    'Parallel parking',
    'Why we rent tuxedos',
    'Why cats rule the internet',
    "Why we ask 'how are you?' and don't wait",
    'Why grown adults collect Beanie Babies',
    'Why we pay for water in bottles',
    'Airport security',
    'Why we yell at sports on TV',
    'Why people microwave fish at work',
    'Why Mondays exist',
    'Hot dogs in packs of 10, buns in packs of 8',
  ] },
  { id: 'g24', text: 'A terrible name for a band', answers: [
    'The Reply-Alls',
    'Printer Jam',
    'Lost Luggage',
    'Bagpipes Anonymous',
    'Dad Jeans',
    'The Unmuted Microphones',
    'The Middle Seats',
    'Dull Knife Parade',
    'Fax Machine Funk',
    'Mild Salsa',
    'The Snooze Buttons',
    'Kevin From Accounting',
    'The Mute Button',
    'Soggy Cereal',
    'Carpool Karaoke Casualties',
    'The Recycling Bins',
    "Grandma's Minivan",
    'Out of Office',
    'Emotional Support Tuba',
    'The Mild Discomforts',
  ] },
  { id: 'g25', text: "The first thing you'd buy if you won the lottery", answers: [
    'A second, smaller lottery ticket',
    'Every seat on a flight so I can lie down',
    'A printer that actually works',
    'A moat',
    "A butler whose only job is to say 'indeed'",
    'A llama. Just one. For now.',
    'A private jet for my cat',
    'Solid gold toilet paper',
    'A hot tub on wheels',
    'The company, so I can give myself a raise',
    'Heated sidewalks',
    'A pool full of pudding',
    'Seven identical outfits, like a cartoon character',
    'A castle, preferably haunted',
    'A robot that folds laundry',
    'A lifetime supply of guacamole',
    "A billboard that says 'I told you so'",
    'My own island, named after me',
    'A giant slide from my bedroom to the kitchen',
    'An elephant. A small one.',
  ] },
  { id: 'g26', text: 'A terrible name for a perfume', answers: [
    'Eau de Gym Bag',
    'Essence of Monday',
    'Wet Parking Garage',
    'Burnt Toast No. 5',
    'Printer Toner Noir',
    "Grandpa's Car (Summer Edition)",
    'Old Library Book',
    'Nervous Sweat',
    'Morning Coffee Breath',
    'Wet Dog Deluxe',
    'Stale Popcorn Nights',
    'Airport Bathroom',
    'Minivan After Soccer Practice',
    'Burnt Microwave Popcorn',
    'Freshly Cut Onion',
    "Dentist's Glove",
    'Chlorine Dream',
    'Garlic Knot',
    'Overripe Banana Chic',
    'Hot Pavement',
  ] },
  { id: 'g27', text: "A surprising thing to find in your grandma's purse", answers: [
    "A switchblade and seven Werther's",
    'A second, smaller grandma',
    'Your baby teeth, alphabetized',
    'A burner phone',
    'Enough napkins to wallpaper a house',
    'A live pigeon named Doug',
    'A rolling pin, for emergencies',
    'Seventy-three expired coupons',
    'A live pigeon she swears followed her home',
    'A peppermint fused to a dollar bill',
    'Enough tissues for a small nation',
    'Brass knuckles',
    'Her phone, which she still cannot unlock',
    'A backup set of teeth',
    "A tiny flask labeled 'cough syrup'",
    'Your report card from 1998',
    'Sugar packets from every restaurant ever',
    'A whole rotisserie chicken',
    'Emergency hard-boiled eggs',
    'A 1987 TV Guide',
  ] },
  { id: 'g28', text: 'A new holiday nobody wants', answers: [
    'National Reply All Day',
    'Mandatory Karaoke Eve',
    'Tax Day 2: The Sequel',
    'Talk Like a Manager Day',
    'Daylight Losing Time',
    'International Printer Appreciation Week',
    'National Stub Your Toe Day',
    'Unpaid Overtime Appreciation Day',
    'Mandatory Group Photo Week',
    'Leftover Fish Friday',
    'Awkward Silence Hour',
    'International Paper Cut Day',
    'Fold Your Laundry Day',
    'Reply to Old Emails Week',
    'Bring Your Parents to Work Day',
    'Second Tuesday',
    'National Traffic Jam Day',
    'Tax Audit Appreciation Day',
    'Monday Eve',
    'Calendar Invite Day',
  ] },
];

// Fits (almost) any prompt. Used for custom prompts and as a last resort.
const GENERIC = [
  'Three raccoons in a trench coat',
  'A strongly worded email',
  'Unlimited breadsticks',
  'A timeshare presentation',
  'An emotional support llama',
  "Whatever's growing in the office fridge",
  'Accidentally hitting Reply All',
  'A mandatory fun day',
  'Free continental breakfast',
  'Jazz hands. Aggressive jazz hands.',
  'A really confident pigeon',
  'Airport carpet',
  "My mom's Facebook comments",
  'A lukewarm Hot Pocket',
  'A haunted spreadsheet',
  'A slightly damp sock',
  'Interpretive dance',
  'An unexpected bagpipe solo',
  'A sad desk salad',
  'Crocs with socks',
  "The Wi-Fi password, but it's wrong",
  'A goose with a grudge',
  'Cargo shorts with 40 pockets',
  'A surprise audit',
  "Grandma's fruitcake from 1998",
  'A 97-slide PowerPoint',
  'The Macarena, but slower',
  'A tiny cowboy hat',
  'Soggy fries',
  'The middle seat',
  'Bees. Just bees.',
  'A motivational poster of a cat',
  'Two kids in a business suit',
  'A very long voicemail',
  'Elevator music, live',
  'Socks and sandals',
];

module.exports = { PROMPTS, GENERIC };
